package brite.outdoor.constants

class PrefConst {
    companion object {
        const val PREF_IS_FIRST_OPEN_APP = "_pref_is_first_open_app"
        const val PREF_IS_FIRST_OPEN_SCREEN_WELCOME="_pref_is_first_open_screen_welcome"
        const val PREF_IS_LOGIN = "_pref_is_login"
        const val PREF_LOGIN_WITH = "_pref_login_with_"
        const val PREF_LAST_SYNC = "_pref_last_sync"
        const val PREF_LAST_SYNC_LOCATION = "_pref_last_sync_location"
        const val PREF_LAST_SYNC_UTENSIL = "_pref_last_sync_utensil"
        const val PREF_PATH_IMAGE_LIST_LOCATION="_pref_path_image_list_location"
        const val PREF_PATH_IMAGE_LIST_UTENSILS="_pref_path_image_list_utensils"
        const val PREF_MULTI_LANGUAGE="_pref_multi_language"
        const val PREF_LANGUAGE="_pref_language"

        const val PREF_USER_ID = "_pref_user_id"
        const val PREF_EMAIL = "_pref_email"
        const val PREF_NAME = "_pref_name"
        const val PREF_STATUS = "_pref_status"
        const val PREF_GENDER = "_pref_gender"
        const val PREF_BIRTHDAY = "_pref_birthday"
        const val PREF_DEVICE_TYPE="_pref_device_type"
        const val PREF_CURRENT_DEVICE_TYPE = "_pref_current_device_type"
        const val PREF_REGISTER_DEVICE_UUID = "_pref_register_device_uuid"
        const val PREF_CURRENT_DEVICE_UUID = "_pref_current_device_uuid"
        const val PREF_VERSION_DATA = "_pref_version_data"
        const val PREF_USER_AVATAR = "_pref_user_avatar"
        const val PREF_TOKEN = "_pref_token"
        const val PREF_FIREBASE_TOKEN = "_pref_firebase_token"
        const val PREF_IS_DELETE = "_pref_is_deleted"
        const val PREF_CREATED_TIME = "_pref_created_time"
        const val PREF_MODIFIED_TIME = "_pref_modified_time"
        const val PREF_LIKE_COUNTS = "_pref_like_counts"
        const val PREF_SHARE_COUNTS = "_pref_share_counts"
        const val PREF_FOLLOW_COUNTS = "_pref_follow_counts"
        const val PREF_URL_PREFIX_AVATAR = "_pref_url_prefix_avatar"
        const val PREF_URL_PREFIX_LOCATION = "_pref_url_prefix_location"
    }
}